// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetLanguage returns the persisted language or empty string if not set.
 */
export function GetLanguage(): $CancellablePromise<string> {
    return $Call.ByID(1915566495);
}

/**
 * SetLanguage persists the application language.
 */
export function SetLanguage(lang: string): $CancellablePromise<boolean> {
    return $Call.ByID(1461740427, lang);
}
