// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * OpenFile opens a file dialog and returns the selected file path. If cancelled path is empty.
 */
export function OpenFolder(basePath: string): $CancellablePromise<$models.DialogResponse> {
    return $Call.ByID(2754864696, basePath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SelectFile(basePath: string, displayName: string, pattern: string): $CancellablePromise<$models.DialogResponse> {
    return $Call.ByID(2150691810, basePath, displayName, pattern).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SelectSaveFile(basePath: string, displayName: string, pattern: string): $CancellablePromise<$models.DialogResponse> {
    return $Call.ByID(144228823, basePath, displayName, pattern).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DialogResponse.createFrom;
