// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ExportInvoicePDF generates a PDF for the given invoice and writes it to outPath.
 * It will create parent directories if necessary and ensure the file has a .pdf extension.
 * ExportInvoicePDF generates a PDF for the given invoice and writes it to outPath.
 * lang is a BCP47 language tag (e.g., "en", "es-ES"). If empty, defaults to English.
 */
export function ExportInvoicePDF(databasePath: string, invoiceID: number, outPath: string, lang: string): $CancellablePromise<void> {
    return $Call.ByID(1145491626, databasePath, invoiceID, outPath, lang);
}
